runtime: go
api_version: go1

service: spa
handlers:
- url: /api/.*
  script: _go_app
- url: /
  static_files: build/index.html
  upload: build/index.html
  expiration: "1h"
- url: /service-worker.js
  static_files: build/service-worker.js
  upload: build/service-worker.js
  expiration: "0s"
- url: /
  static_dir: build
  expiration: "10h"

skip_files:
  - node_modules/*
  - src/*
  - public/*
  - package.json
  - package-lock.json
  - README.md
